# Generated by Django 3.1.2 on 2020-10-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201013_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subect',
            new_name='subject',
        ),
    ]
