# Generated by Django 3.1.2 on 2020-10-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20201020_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='followed',
            new_name='followedBy',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='follower',
            new_name='following',
        ),
    ]
