# Generated by Django 3.1.2 on 2020-10-22 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20201020_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='followedBy',
        ),
        migrations.AddField(
            model_name='following',
            name='followedby',
            field=models.ManyToManyField(related_name='followedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='following',
            name='following',
        ),
        migrations.AddField(
            model_name='following',
            name='following',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
