# Generated by Django 3.1.2 on 2020-11-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20201022_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
