# Generated by Django 3.1.2 on 2020-11-26 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='followedby',
        ),
        migrations.AddField(
            model_name='following',
            name='followedby',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='followedby', to='network.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='following',
            name='following',
        ),
        migrations.AddField(
            model_name='following',
            name='following',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='network.user'),
            preserve_default=False,
        ),
    ]
