# Generated by Django 3.1.2 on 2020-12-02 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_post_likecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='count',
        ),
    ]
