# Generated by Django 3.1.2 on 2020-12-02 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='likedpost',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='network.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likes',
            name='liked',
            field=models.BooleanField(),
        ),
    ]
