# Generated by Django 3.1.2 on 2020-12-02 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20201201_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='likedpost',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likecount',
        ),
        migrations.AddField(
            model_name='likes',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='likes',
            name='liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.post'),
        ),
    ]
