# Generated by Django 3.1.2 on 2020-12-02 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20201201_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='count',
        ),
        migrations.AddField(
            model_name='likes',
            name='likedpost',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='network.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='likes',
            name='liked',
            field=models.BooleanField(),
        ),
    ]
